import React, { ReactNode } from 'react';
import Head from 'next/head';
import { Navbar } from './Navbar';

interface Props {
  title: string;
  children: ReactNode | ReactNode[];
  pageDescription: string;
  imageUrl?: string
}

export const Layout = ({ title, children, pageDescription, imageUrl }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <meta name='og:title' content={title} />
        <meta name='og:description' content={pageDescription} />

        {
          imageUrl && <meta name='og:image' content={imageUrl} />
        }
      </Head>
      <div className='container'>
        
        <Navbar />
        {/* <ButtonWhatsapp />

        <Header/> */}

        <main className='main' >
          {children}
        </main>

        {/* <Footer /> */}
      </div>
    </>
  )
}
